apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: laravel-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: longhorn   # <- uncomment and set to whatever storage
                                 #    class your Rancher cluster provides
